"""Postgres backend for the MCP SQL-tool server (asyncpg).

Mirrors the parent app's PgDBClient approach: PgDBClient inherits the
DBClient interface and overrides only the primitives. Tool SQL uses '?'
placeholders on metadata_file/pages only, translated to $n here.

The public schema below must stay in lockstep with the parent app's
db_client_pg.py — both processes CREATE TABLE IF NOT EXISTS against the
same database and whichever connects first wins (same contract as the
existing SQLite mirror).
"""

from __future__ import annotations

import re
from typing import Any

import asyncpg

from app.engines.config import get_database_url
from app.infra.db_client import DBClient
from app.utils.logger import logger

SCHEMA_PG = """
CREATE TABLE IF NOT EXISTS "user" (
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    email TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    last_login TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS session (
    session_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES "user"(user_id),
    session_name TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS metadata_file (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id INTEGER NOT NULL REFERENCES session(session_id),
    user_id INTEGER NOT NULL REFERENCES "user"(user_id),
    type TEXT NOT NULL,
    total_pages INTEGER NOT NULL DEFAULT 0,
    file_name TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    status_message TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS conversation (
    message_id TEXT PRIMARY KEY,
    session_id INTEGER NOT NULL REFERENCES session(session_id),
    user_id INTEGER NOT NULL REFERENCES "user"(user_id),
    sender TEXT NOT NULL,
    message_text TEXT NOT NULL,
    file_id INTEGER REFERENCES metadata_file(id),
    timestamp TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS pages (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    metadata_file_id INTEGER NOT NULL REFERENCES metadata_file(id),
    page INTEGER NOT NULL,
    agent_extracted TEXT,
    status TEXT NOT NULL DEFAULT 'pending',
    status_message TEXT
);

INSERT INTO "user" (user_id, username, email, password_hash)
VALUES (1, 'dev', 'dev@local', 'not-a-real-hash')
ON CONFLICT (user_id) DO NOTHING;

SELECT setval(
    pg_get_serial_sequence('"user"', 'user_id'),
    GREATEST((SELECT COALESCE(MAX(user_id), 1) FROM "user"), 1)
);
"""

_PK_BY_TABLE = {
    "metadata_file": "id",
    "pages": "id",
    "session": "session_id",
    '"user"': "user_id",
}

_INSERT_RE = re.compile(r"^\s*INSERT\s+INTO\s+(\S+)", re.IGNORECASE)


def _translate_placeholders(sql: str) -> str:
    """Rewrite sqlite-style '?' placeholders to asyncpg '$n'."""
    counter = 0

    def _next(_match: re.Match) -> str:
        nonlocal counter
        counter += 1
        return f"${counter}"

    return re.sub(r"\?", _next, sql)


class PgDBClient(DBClient):
    """asyncpg-backed drop-in for DBClient."""

    def __init__(self) -> None:
        self._dsn = get_database_url()
        self._pool: asyncpg.Pool | None = None

    async def connect(self) -> None:
        self._pool = await asyncpg.create_pool(self._dsn, min_size=1, max_size=5)
        async with self._pool.acquire() as conn:
            await conn.execute(SCHEMA_PG)
        logger.info("Postgres pool connected (schema applied)")

    async def close(self) -> None:
        if self._pool is not None:
            await self._pool.close()
            self._pool = None

    @property
    def pool(self) -> asyncpg.Pool:
        if self._pool is None:
            raise RuntimeError("Database not connected")
        return self._pool

    async def fetchone(self, sql: str, params: tuple = ()) -> dict[str, Any] | None:
        row = await self.pool.fetchrow(_translate_placeholders(sql), *params)
        return dict(row) if row else None

    async def fetchall(self, sql: str, params: tuple = ()) -> list[dict[str, Any]]:
        rows = await self.pool.fetch(_translate_placeholders(sql), *params)
        return [dict(r) for r in rows]

    async def execute(self, sql: str, params: tuple = ()) -> int:
        """Run a statement; INSERTs into id-bearing tables return the new id
        (lastrowid parity with the SQLite client)."""
        translated = _translate_placeholders(sql)
        insert = _INSERT_RE.match(translated)
        table = insert.group(1).lower() if insert else None
        pk = _PK_BY_TABLE.get(table) if table else None
        if pk and "returning" not in translated.lower():
            value = await self.pool.fetchval(
                f"{translated.rstrip().rstrip(';')} RETURNING {pk}", *params
            )
            return int(value) if value is not None else 0
        await self.pool.execute(translated, *params)
        return 0

    async def execute_returning(
        self, sql: str, params: tuple = ()
    ) -> dict[str, Any] | None:
        row = await self.pool.fetchrow(_translate_placeholders(sql), *params)
        return dict(row) if row else None


def build_db_client() -> DBClient:
    """Pick the backend from env: DATABASE_URL set -> Postgres, else SQLite."""
    if get_database_url():
        return PgDBClient()
    return DBClient()
