"""PostgreSQL data access for application and extraction state."""

from __future__ import annotations

import logging
from typing import Any
from uuid import uuid4

import asyncpg

from config.settings import Settings

logger = logging.getLogger(__name__)

_SCHEMA_SQL = """
CREATE TABLE IF NOT EXISTS "user" (
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    email TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    last_login TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS session (
    session_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES "user"(user_id),
    session_name TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS metadata_file (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id INTEGER NOT NULL REFERENCES session(session_id),
    user_id INTEGER NOT NULL REFERENCES "user"(user_id),
    type TEXT NOT NULL,
    total_pages INTEGER NOT NULL DEFAULT 0,
    file_name TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    status_message TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS conversation (
    message_id TEXT PRIMARY KEY,
    session_id INTEGER NOT NULL REFERENCES session(session_id),
    user_id INTEGER NOT NULL REFERENCES "user"(user_id),
    sender TEXT NOT NULL,
    message_text TEXT NOT NULL,
    file_id INTEGER REFERENCES metadata_file(id),
    timestamp TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS pages (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    metadata_file_id INTEGER NOT NULL REFERENCES metadata_file(id),
    page INTEGER NOT NULL,
    agent_extracted TEXT,
    status TEXT NOT NULL DEFAULT 'pending',
    status_message TEXT
);

CREATE TABLE IF NOT EXISTS file_blob (
    blob_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    blake3 TEXT NOT NULL,
    minio_key TEXT NOT NULL,
    content_type TEXT NOT NULL,
    size_bytes BIGINT NOT NULL,
    page_count INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(user_id, blake3)
);

DROP INDEX IF EXISTS idx_file_blob_user_hash;

CREATE TABLE IF NOT EXISTS file_blob_page (
    blob_id INTEGER NOT NULL REFERENCES file_blob(blob_id),
    page INTEGER NOT NULL,
    page_blake3 TEXT NOT NULL,
    page_minio_key TEXT NOT NULL,
    PRIMARY KEY (blob_id, page)
);

CREATE INDEX IF NOT EXISTS idx_file_blob_page_hash
    ON file_blob_page(page_blake3);

CREATE TABLE IF NOT EXISTS blob_extraction (
    user_id INTEGER NOT NULL,
    page_blake3 TEXT NOT NULL,
    extraction_json TEXT NOT NULL,
    ocr_model TEXT,
    schema_version TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, page_blake3)
);

CREATE TABLE IF NOT EXISTS metadata_file_blob (
    metadata_file_id INTEGER PRIMARY KEY,
    blob_id INTEGER NOT NULL REFERENCES file_blob(blob_id)
);

INSERT INTO "user" (user_id, username, email, password_hash)
VALUES (1, 'dev', 'dev@local', 'not-a-real-hash')
ON CONFLICT (user_id) DO NOTHING;
"""


def _affected_rows(command_status: str) -> int:
    """Return the row count from an asyncpg command status."""
    final_token = command_status.rsplit(" ", 1)[-1]
    return int(final_token) if final_token.isdigit() else 0


class AppDBClient:
    """Async PostgreSQL client for application-owned data."""

    def __init__(self, settings: Settings) -> None:
        """Store database settings without opening a connection."""
        self._dsn = settings.database_url
        self._pool: asyncpg.Pool | None = None

    async def connect(self) -> None:
        """Open the pool and apply the idempotent schema."""
        self._pool = await asyncpg.create_pool(self._dsn, min_size=1, max_size=10)
        async with self.pool.acquire() as connection:
            await connection.execute(_SCHEMA_SQL)
        await self.reset_user_id_sequence()
        logger.info("PostgreSQL pool connected and schema applied")

    async def close(self) -> None:
        """Close the connection pool."""
        if self._pool is not None:
            await self._pool.close()
            self._pool = None

    @property
    def pool(self) -> asyncpg.Pool:
        """Return the active pool.

        Raises:
            RuntimeError: If connect has not completed.
        """
        if self._pool is None:
            raise RuntimeError("Database not connected")
        return self._pool

    async def reset_user_id_sequence(self) -> None:
        """Advance the user sequence past explicit seed rows."""
        await self.pool.execute(
            """SELECT setval(
                   pg_get_serial_sequence('"user"', 'user_id'),
                   GREATEST((SELECT COALESCE(MAX(user_id), 1) FROM "user"), 1)
               )"""
        )

    async def fetchone(self, sql: str, params: tuple = ()) -> dict[str, Any] | None:
        """Fetch one row as a dictionary."""
        row = await self.pool.fetchrow(sql, *params)
        return dict(row) if row else None

    async def fetchall(self, sql: str, params: tuple = ()) -> list[dict[str, Any]]:
        """Fetch all rows as dictionaries."""
        rows = await self.pool.fetch(sql, *params)
        return [dict(row) for row in rows]

    async def fetchval(self, sql: str, params: tuple = ()) -> Any:
        """Fetch the first column from one row."""
        return await self.pool.fetchval(sql, *params)

    async def execute(self, sql: str, params: tuple = ()) -> int:
        """Run a statement and return its affected-row count."""
        command_status = await self.pool.execute(sql, *params)
        return _affected_rows(command_status)

    async def get_user_by_username(self, username: str) -> dict[str, Any] | None:
        """Return an authentication row by username."""
        return await self.fetchone(
            'SELECT user_id, username, email, password_hash FROM "user" '
            "WHERE username = $1",
            (username,),
        )

    async def create_user(self, username: str, email: str, password_hash: str) -> int:
        """Create a user and return its ID."""
        user_id = await self.fetchval(
            'INSERT INTO "user" (username, email, password_hash) '
            "VALUES ($1, $2, $3) RETURNING user_id",
            (username, email, password_hash),
        )
        return int(user_id)

    async def update_last_login(self, user_id: int) -> None:
        """Set the user's last-login timestamp."""
        await self.execute(
            'UPDATE "user" SET last_login = CURRENT_TIMESTAMP WHERE user_id = $1',
            (user_id,),
        )

    async def get_session_owner(self, session_id: int) -> int | None:
        """Return the user that owns a session."""
        row = await self.fetchone(
            "SELECT user_id FROM session WHERE session_id = $1",
            (session_id,),
        )
        return row["user_id"] if row else None

    async def create_session(
        self, user_id: int, session_name: str | None = None
    ) -> int:
        """Create a session and return its ID."""
        session_id = await self.fetchval(
            "INSERT INTO session (user_id, session_name) "
            "VALUES ($1, $2) RETURNING session_id",
            (user_id, session_name),
        )
        return int(session_id)

    async def get_conversation_history(
        self, session_id: int, limit: int = 10
    ) -> list[dict[str, Any]]:
        """Return recent session messages in reverse time order."""
        return await self.fetchall(
            """
            SELECT sender, message_text, file_id, timestamp
            FROM conversation
            WHERE session_id = $1
            ORDER BY timestamp DESC
            LIMIT $2
            """,
            (session_id, limit),
        )

    async def save_message(
        self,
        session_id: int,
        user_id: int,
        sender: str,
        message_text: str,
        file_id: int | None = None,
    ) -> str:
        """Store a conversation message and return its ID."""
        message_id = uuid4().hex
        await self.execute(
            """
            INSERT INTO conversation
                (message_id, session_id, user_id, sender, message_text, file_id)
            VALUES ($1, $2, $3, $4, $5, $6)
            """,
            (message_id, session_id, user_id, sender, message_text, file_id),
        )
        return message_id

    async def update_session_timestamp(self, session_id: int) -> None:
        """Mark a session as recently updated."""
        await self.execute(
            "UPDATE session SET updated_at = CURRENT_TIMESTAMP WHERE session_id = $1",
            (session_id,),
        )

    async def get_session_files(self, session_id: int) -> list[dict[str, Any]]:
        """Return files uploaded in a session."""
        return await self.fetchall(
            "SELECT * FROM metadata_file WHERE session_id = $1 ORDER BY created_at",
            (session_id,),
        )

    async def get_sessions(self, user_id: int) -> list[dict[str, Any]]:
        """Return a user's sessions in reverse update order."""
        return await self.fetchall(
            """
            SELECT session_id, session_name, created_at, updated_at
            FROM session
            WHERE user_id = $1
            ORDER BY updated_at DESC
            """,
            (user_id,),
        )

    async def get_session_messages(self, session_id: int) -> list[dict[str, Any]]:
        """Return session messages in chronological order."""
        return await self.fetchall(
            """
            SELECT sender, message_text, file_id, timestamp
            FROM conversation
            WHERE session_id = $1
            ORDER BY timestamp ASC
            """,
            (session_id,),
        )

    async def find_blob(self, user_id: int, blake3: str) -> dict[str, Any] | None:
        """Find a content blob in a user's keyspace."""
        return await self.fetchone(
            "SELECT * FROM file_blob WHERE user_id = $1 AND blake3 = $2",
            (user_id, blake3),
        )

    async def insert_blob(
        self,
        *,
        user_id: int,
        blake3: str,
        minio_key: str,
        content_type: str,
        size_bytes: int,
        page_count: int,
    ) -> int:
        """Store blob metadata and return its ID."""
        blob_id = await self.fetchval(
            """
            INSERT INTO file_blob
                (user_id, blake3, minio_key, content_type, size_bytes, page_count)
            VALUES ($1, $2, $3, $4, $5, $6)
            RETURNING blob_id
            """,
            (user_id, blake3, minio_key, content_type, size_bytes, page_count),
        )
        return int(blob_id)

    async def upsert_blob_page(
        self,
        *,
        blob_id: int,
        page: int,
        page_blake3: str,
        page_minio_key: str,
    ) -> None:
        """Create or update one page in a content blob."""
        await self.execute(
            """
            INSERT INTO file_blob_page (blob_id, page, page_blake3, page_minio_key)
            VALUES ($1, $2, $3, $4)
            ON CONFLICT(blob_id, page) DO UPDATE SET
                page_blake3 = EXCLUDED.page_blake3,
                page_minio_key = EXCLUDED.page_minio_key
            """,
            (blob_id, page, page_blake3, page_minio_key),
        )

    async def get_cached_extraction(
        self, user_id: int, page_blake3: str
    ) -> dict[str, Any] | None:
        """Return a stored extraction by user and page hash."""
        return await self.fetchone(
            """
            SELECT extraction_json, ocr_model, schema_version, created_at
            FROM blob_extraction
            WHERE user_id = $1 AND page_blake3 = $2
            """,
            (user_id, page_blake3),
        )

    async def upsert_extraction(
        self,
        *,
        user_id: int,
        page_blake3: str,
        extraction_json: str,
        ocr_model: str | None,
        schema_version: str | None,
    ) -> None:
        """Create or update a stored page extraction."""
        await self.execute(
            """
            INSERT INTO blob_extraction
                (user_id, page_blake3, extraction_json, ocr_model, schema_version)
            VALUES ($1, $2, $3, $4, $5)
            ON CONFLICT(user_id, page_blake3) DO UPDATE SET
                extraction_json = EXCLUDED.extraction_json,
                ocr_model = EXCLUDED.ocr_model,
                schema_version = EXCLUDED.schema_version
            """,
            (user_id, page_blake3, extraction_json, ocr_model, schema_version),
        )

    async def link_metadata_file_blob(
        self, metadata_file_id: int, blob_id: int
    ) -> None:
        """Link an uploaded file to its content blob."""
        await self.execute(
            """
            INSERT INTO metadata_file_blob (metadata_file_id, blob_id)
            VALUES ($1, $2)
            ON CONFLICT(metadata_file_id) DO UPDATE SET blob_id = EXCLUDED.blob_id
            """,
            (metadata_file_id, blob_id),
        )
