"""Postgres implementation of the app data layer (asyncpg).

PgDBClient inherits every domain method from AppDBClient and overrides only
the five primitives (connect/close/fetchone/fetchall/execute) plus the three
user-table queries (``user`` is a reserved word in Postgres and must be
quoted). Raw '?'-placeholder SQL from ingest/tasks/orchestrator is translated
to $n placeholders here, so callers never know which backend they run on.

NOTE: production cutover to Postgres is gated on the MCP SQL-tool server
being ported too — until then the SQL agent reads SQLite, and pointing the
app at DATABASE_URL alone would split-brain agent-visible data.
"""

from __future__ import annotations

import logging
import re
from typing import Any

import asyncpg

from app.services.extraction.infra.db_client import AppDBClient
from config.settings import Settings

logger = logging.getLogger(__name__)

_SCHEMA_PG = """
CREATE TABLE IF NOT EXISTS "user" (
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    email TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    last_login TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS session (
    session_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES "user"(user_id),
    session_name TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS metadata_file (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id INTEGER NOT NULL REFERENCES session(session_id),
    user_id INTEGER NOT NULL REFERENCES "user"(user_id),
    type TEXT NOT NULL,
    total_pages INTEGER NOT NULL DEFAULT 0,
    file_name TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    status_message TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS conversation (
    message_id TEXT PRIMARY KEY,
    session_id INTEGER NOT NULL REFERENCES session(session_id),
    user_id INTEGER NOT NULL REFERENCES "user"(user_id),
    sender TEXT NOT NULL,
    message_text TEXT NOT NULL,
    file_id INTEGER REFERENCES metadata_file(id),
    timestamp TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS pages (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    metadata_file_id INTEGER NOT NULL REFERENCES metadata_file(id),
    page INTEGER NOT NULL,
    agent_extracted TEXT,
    status TEXT NOT NULL DEFAULT 'pending',
    status_message TEXT
);

CREATE TABLE IF NOT EXISTS file_blob (
    blob_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    blake3 TEXT NOT NULL,
    minio_key TEXT NOT NULL,
    content_type TEXT NOT NULL,
    size_bytes BIGINT NOT NULL,
    page_count INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(user_id, blake3)
);

CREATE INDEX IF NOT EXISTS idx_file_blob_user_hash
    ON file_blob(user_id, blake3);

CREATE TABLE IF NOT EXISTS file_blob_page (
    blob_id INTEGER NOT NULL REFERENCES file_blob(blob_id),
    page INTEGER NOT NULL,
    page_blake3 TEXT NOT NULL,
    page_minio_key TEXT NOT NULL,
    PRIMARY KEY (blob_id, page)
);

CREATE INDEX IF NOT EXISTS idx_file_blob_page_hash
    ON file_blob_page(page_blake3);

CREATE TABLE IF NOT EXISTS blob_extraction (
    user_id INTEGER NOT NULL,
    page_blake3 TEXT NOT NULL,
    extraction_json TEXT NOT NULL,
    ocr_model TEXT,
    schema_version TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, page_blake3)
);

CREATE TABLE IF NOT EXISTS metadata_file_blob (
    metadata_file_id INTEGER PRIMARY KEY,
    blob_id INTEGER NOT NULL REFERENCES file_blob(blob_id)
);

INSERT INTO "user" (user_id, username, email, password_hash)
VALUES (1, 'dev', 'dev@local', 'not-a-real-hash')
ON CONFLICT (user_id) DO NOTHING;
"""

# Tables whose auto-generated integer id callers consume via execute().
_PK_BY_TABLE = {
    "user": "user_id",
    '"user"': "user_id",
    "session": "session_id",
    "metadata_file": "id",
    "pages": "id",
    "file_blob": "blob_id",
}

_INSERT_RE = re.compile(r"^\s*INSERT\s+INTO\s+(\S+)", re.IGNORECASE)


def _translate_placeholders(sql: str) -> str:
    """Rewrite sqlite-style '?' placeholders to asyncpg '$n'."""
    counter = 0

    def _next(_match: re.Match) -> str:
        nonlocal counter
        counter += 1
        return f"${counter}"

    return re.sub(r"\?", _next, sql)


class PgDBClient(AppDBClient):
    """asyncpg-backed drop-in for AppDBClient (see module docstring)."""

    def __init__(self, settings: Settings) -> None:
        self._dsn = settings.database_url
        self._pool: asyncpg.Pool | None = None

    async def connect(self) -> None:
        self._pool = await asyncpg.create_pool(self._dsn, min_size=1, max_size=10)
        async with self._pool.acquire() as conn:
            await conn.execute(_SCHEMA_PG)
        await self.reset_user_id_sequence()
        logger.info("Postgres pool connected (schema applied)")

    async def close(self) -> None:
        if self._pool is not None:
            await self._pool.close()
            self._pool = None

    async def reset_user_id_sequence(self) -> None:
        """Advance the user_id sequence past explicitly-seeded rows so the
        next auto id never collides with the dev bootstrap row."""
        async with self.pool.acquire() as conn:
            await conn.execute(
                """SELECT setval(
                       pg_get_serial_sequence('"user"', 'user_id'),
                       GREATEST((SELECT COALESCE(MAX(user_id), 1) FROM "user"), 1)
                   )"""
            )

    @property
    def pool(self) -> asyncpg.Pool:
        if self._pool is None:
            raise RuntimeError("Database not connected")
        return self._pool

    async def fetchone(self, sql: str, params: tuple = ()) -> dict[str, Any] | None:
        row = await self.pool.fetchrow(_translate_placeholders(sql), *params)
        return dict(row) if row else None

    async def fetchall(self, sql: str, params: tuple = ()) -> list[dict[str, Any]]:
        rows = await self.pool.fetch(_translate_placeholders(sql), *params)
        return [dict(r) for r in rows]

    async def execute(self, sql: str, params: tuple = ()) -> int:
        """Run a statement; for INSERTs into id-bearing tables, return the
        new id (lastrowid parity with the SQLite client)."""
        translated = _translate_placeholders(sql)
        insert = _INSERT_RE.match(translated)
        table = insert.group(1).lower() if insert else None
        pk = _PK_BY_TABLE.get(table) if table else None
        if pk and "returning" not in translated.lower():
            value = await self.pool.fetchval(
                f"{translated.rstrip().rstrip(';')} RETURNING {pk}", *params
            )
            return int(value) if value is not None else 0
        await self.pool.execute(translated, *params)
        return 0

    async def get_user_by_username(self, username: str) -> dict[str, Any] | None:
        return await self.fetchone(
            'SELECT user_id, username, email, password_hash FROM "user" '
            "WHERE username = ?",
            (username,),
        )

    async def create_user(self, username: str, email: str, password_hash: str) -> int:
        return await self.execute(
            'INSERT INTO "user" (username, email, password_hash) VALUES (?, ?, ?)',
            (username, email, password_hash),
        )

    async def update_last_login(self, user_id: int) -> None:
        await self.execute(
            'UPDATE "user" SET last_login = CURRENT_TIMESTAMP WHERE user_id = ?',
            (user_id,),
        )


def build_db_client(settings: Settings) -> AppDBClient:
    """Pick the data-layer backend from settings.

    Args:
        settings: App settings; DATABASE_URL set -> Postgres, else SQLite.

    Returns:
        Connected-not-yet client (caller runs connect()).
    """
    if settings.database_url:
        return PgDBClient(settings)
    return AppDBClient(settings)
