"""PostgreSQL data access for the receipt archive service."""

from __future__ import annotations

from typing import Any

import asyncpg

from app.engines.config import get_database_url
from app.utils.logger import logger

SCHEMA_SQL = """
CREATE TABLE IF NOT EXISTS "user" (
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    email TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    last_login TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS session (
    session_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES "user"(user_id),
    session_name TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS metadata_file (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id INTEGER NOT NULL REFERENCES session(session_id),
    user_id INTEGER NOT NULL REFERENCES "user"(user_id),
    type TEXT NOT NULL,
    total_pages INTEGER NOT NULL DEFAULT 0,
    file_name TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    status_message TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS conversation (
    message_id TEXT PRIMARY KEY,
    session_id INTEGER NOT NULL REFERENCES session(session_id),
    user_id INTEGER NOT NULL REFERENCES "user"(user_id),
    sender TEXT NOT NULL,
    message_text TEXT NOT NULL,
    file_id INTEGER REFERENCES metadata_file(id),
    timestamp TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS pages (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    metadata_file_id INTEGER NOT NULL REFERENCES metadata_file(id),
    page INTEGER NOT NULL,
    agent_extracted TEXT,
    status TEXT NOT NULL DEFAULT 'pending',
    status_message TEXT
);

INSERT INTO "user" (user_id, username, email, password_hash)
VALUES (1, 'dev', 'dev@local', 'not-a-real-hash')
ON CONFLICT (user_id) DO NOTHING;
"""


def _affected_rows(command_status: str) -> int:
    """Return the row count from an asyncpg command status."""
    final_token = command_status.rsplit(" ", 1)[-1]
    return int(final_token) if final_token.isdigit() else 0


class DBClient:
    """Async PostgreSQL client for archive metadata."""

    def __init__(self) -> None:
        """Store the configured DSN without opening a connection."""
        self._dsn = get_database_url()
        self._pool: asyncpg.Pool | None = None

    async def connect(self) -> None:
        """Open the pool and apply the idempotent archive schema."""
        self._pool = await asyncpg.create_pool(self._dsn, min_size=1, max_size=5)
        async with self.pool.acquire() as connection:
            await connection.execute(SCHEMA_SQL)
        await self.pool.execute(
            """SELECT setval(
                   pg_get_serial_sequence('"user"', 'user_id'),
                   GREATEST((SELECT COALESCE(MAX(user_id), 1) FROM "user"), 1)
               )"""
        )
        logger.info("PostgreSQL pool connected and archive schema applied")

    async def close(self) -> None:
        """Close the connection pool."""
        if self._pool is not None:
            await self._pool.close()
            self._pool = None

    @property
    def pool(self) -> asyncpg.Pool:
        """Return the active pool.

        Raises:
            RuntimeError: If connect has not completed.
        """
        if self._pool is None:
            raise RuntimeError("Database not connected")
        return self._pool

    async def fetchone(self, sql: str, params: tuple = ()) -> dict[str, Any] | None:
        """Fetch one row as a dictionary."""
        row = await self.pool.fetchrow(sql, *params)
        return dict(row) if row else None

    async def fetchall(self, sql: str, params: tuple = ()) -> list[dict[str, Any]]:
        """Fetch all rows as dictionaries."""
        rows = await self.pool.fetch(sql, *params)
        return [dict(row) for row in rows]

    async def fetchval(self, sql: str, params: tuple = ()) -> Any:
        """Fetch the first column from one row."""
        return await self.pool.fetchval(sql, *params)

    async def execute(self, sql: str, params: tuple = ()) -> int:
        """Run a statement and return its affected-row count."""
        command_status = await self.pool.execute(sql, *params)
        return _affected_rows(command_status)
