"""Postgres-backed sheet storage for the ledger.

Data model is user -> spreadsheets -> sheets, mirroring Excel/GSheets.
`ledger_spreadsheet` owns tenancy (user_id); `ledger_sheet.workspace` is
an FK to it. One row per sheet tab; the cell grid is a single JSONB 2D
array. All mutations run read-modify-write inside a transaction with
FOR UPDATE row locking, which preserves spreadsheet semantics with
receipt-scale data (hundreds of rows per tab). Revisit granularity only
if tabs grow far beyond that.

`user_id` deliberately has no FK to the app's "user" table: this schema
is owned by mcp-ledger and must stand alone (the server can boot before
the app tables exist, and user 0 is the system owner of default/legacy
workspaces).
"""

from __future__ import annotations

import json
import logging
import os
import uuid
from typing import Any, Callable, Optional

import asyncpg

logger = logging.getLogger(__name__)

DEFAULT_WORKSPACE = os.environ.get("LEDGER_WORKSPACE", "default")

SYSTEM_USER_ID = 0  # owner of the default workspace and adopted legacy rows

_SCHEMA = """
CREATE TABLE IF NOT EXISTS ledger_spreadsheet (
    spreadsheet_id TEXT PRIMARY KEY,
    user_id INTEGER NOT NULL,
    name TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (user_id, name)
);

CREATE TABLE IF NOT EXISTS ledger_sheet (
    sheet_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace TEXT NOT NULL,
    title TEXT NOT NULL,
    position INTEGER NOT NULL DEFAULT 0,
    grid JSONB NOT NULL DEFAULT '[]',
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (workspace, title)
);

-- Adopt pre-tenancy workspaces (sheets without a spreadsheet row) as
-- system-owned spreadsheets so the FK below always holds.
INSERT INTO ledger_spreadsheet (spreadsheet_id, user_id, name)
SELECT DISTINCT workspace, 0, workspace FROM ledger_sheet
ON CONFLICT DO NOTHING;

DO $$
BEGIN
    ALTER TABLE ledger_sheet
        ADD CONSTRAINT ledger_sheet_workspace_fkey
        FOREIGN KEY (workspace)
        REFERENCES ledger_spreadsheet (spreadsheet_id)
        ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
"""


class SheetNotFoundError(Exception):
    """Raised when a sheet title does not exist in the workspace."""


class SheetExistsError(Exception):
    """Raised when creating a sheet whose title is already taken."""


class SpreadsheetNotFoundError(Exception):
    """Raised when a spreadsheet id does not exist."""


class SpreadsheetExistsError(Exception):
    """Raised when a user already has a spreadsheet with that name."""


class LedgerStore:
    """Sheet CRUD + grid read/modify/write on Postgres."""

    def __init__(self, dsn: str) -> None:
        self._dsn = dsn
        self._pool: asyncpg.Pool | None = None

    async def connect(self) -> None:
        self._pool = await asyncpg.create_pool(self._dsn, min_size=1, max_size=5)
        async with self._pool.acquire() as conn:
            await conn.execute(_SCHEMA)
        logger.info("Ledger store connected (schema applied)")

    async def close(self) -> None:
        if self._pool is not None:
            await self._pool.close()
            self._pool = None

    @property
    def pool(self) -> asyncpg.Pool:
        if self._pool is None:
            raise RuntimeError("Ledger store not connected")
        return self._pool

    async def create_spreadsheet(self, user_id: int, name: str) -> dict[str, Any]:
        """Create a spreadsheet owned by a user.

        Args:
            user_id: Owning user.
            name: Display name, unique per user.

        Returns:
            Dict with spreadsheetId (opaque hex key) and name.

        Raises:
            SpreadsheetExistsError: If the user already has that name.
        """
        spreadsheet_id = uuid.uuid4().hex
        try:
            await self.pool.execute(
                "INSERT INTO ledger_spreadsheet (spreadsheet_id, user_id, name) "
                "VALUES ($1, $2, $3)",
                spreadsheet_id,
                user_id,
                name,
            )
        except asyncpg.UniqueViolationError:
            raise SpreadsheetExistsError(
                f"Spreadsheet '{name}' already exists"
            ) from None
        return {"spreadsheetId": spreadsheet_id, "name": name}

    async def list_spreadsheets(self, user_id: int) -> list[dict[str, Any]]:
        rows = await self.pool.fetch(
            "SELECT spreadsheet_id, name FROM ledger_spreadsheet "
            "WHERE user_id = $1 ORDER BY created_at, spreadsheet_id",
            user_id,
        )
        return [{"spreadsheetId": r["spreadsheet_id"], "name": r["name"]} for r in rows]

    async def get_spreadsheet(self, spreadsheet_id: str) -> dict[str, Any]:
        row = await self.pool.fetchrow(
            "SELECT spreadsheet_id, user_id, name FROM ledger_spreadsheet "
            "WHERE spreadsheet_id = $1",
            spreadsheet_id,
        )
        if row is None:
            raise SpreadsheetNotFoundError(f"Spreadsheet '{spreadsheet_id}' not found")
        return {
            "spreadsheetId": row["spreadsheet_id"],
            "userId": row["user_id"],
            "name": row["name"],
        }

    async def rename_spreadsheet(self, spreadsheet_id: str, new_name: str) -> None:
        try:
            status = await self.pool.execute(
                "UPDATE ledger_spreadsheet SET name = $2 WHERE spreadsheet_id = $1",
                spreadsheet_id,
                new_name,
            )
        except asyncpg.UniqueViolationError:
            raise SpreadsheetExistsError(
                f"Spreadsheet '{new_name}' already exists"
            ) from None
        if status == "UPDATE 0":
            raise SpreadsheetNotFoundError(f"Spreadsheet '{spreadsheet_id}' not found")

    async def delete_spreadsheet(self, spreadsheet_id: str) -> None:
        """Delete a spreadsheet; its sheets go with it (FK cascade)."""
        status = await self.pool.execute(
            "DELETE FROM ledger_spreadsheet WHERE spreadsheet_id = $1",
            spreadsheet_id,
        )
        if status == "DELETE 0":
            raise SpreadsheetNotFoundError(f"Spreadsheet '{spreadsheet_id}' not found")

    async def ensure_spreadsheet(
        self, workspace: str, user_id: int = SYSTEM_USER_ID
    ) -> None:
        """Idempotently provision a workspace-keyed spreadsheet.

        Used for the server's default workspace, whose key comes from env
        rather than create_spreadsheet, so sheet writes satisfy the FK.
        """
        await self.pool.execute(
            "INSERT INTO ledger_spreadsheet (spreadsheet_id, user_id, name) "
            "VALUES ($1, $2, $1) ON CONFLICT DO NOTHING",
            workspace,
            user_id,
        )

    async def list_sheets(self, workspace: str) -> list[dict[str, Any]]:
        rows = await self.pool.fetch(
            "SELECT sheet_id, title, position FROM ledger_sheet "
            "WHERE workspace = $1 ORDER BY position, sheet_id",
            workspace,
        )
        return [
            {"title": r["title"], "sheetId": r["sheet_id"], "index": i}
            for i, r in enumerate(rows)
        ]

    async def get_grid(self, workspace: str, title: str) -> list[list[Any]]:
        row = await self.pool.fetchrow(
            "SELECT grid FROM ledger_sheet WHERE workspace = $1 AND title = $2",
            workspace,
            title,
        )
        if row is None:
            raise SheetNotFoundError(f"Sheet '{title}' not found")
        return json.loads(row["grid"])

    async def create_sheet(
        self, workspace: str, title: str, grid: Optional[list[list[Any]]] = None
    ) -> dict[str, Any]:
        try:
            row = await self.pool.fetchrow(
                "INSERT INTO ledger_sheet (workspace, title, position, grid) "
                "VALUES ($1, $2, "
                "  COALESCE((SELECT MAX(position) + 1 FROM ledger_sheet "
                "            WHERE workspace = $1), 0), "
                "  $3) "
                "RETURNING sheet_id, title, position",
                workspace,
                title,
                json.dumps(grid or []),
            )
        except asyncpg.UniqueViolationError:
            raise SheetExistsError(f"Sheet '{title}' already exists") from None
        except asyncpg.ForeignKeyViolationError:
            raise SpreadsheetNotFoundError(
                f"Spreadsheet '{workspace}' not found"
            ) from None
        return {
            "sheetId": row["sheet_id"],
            "title": row["title"],
            "index": row["position"],
        }

    async def rename_sheet(self, workspace: str, title: str, new_name: str) -> None:
        status = await self.pool.execute(
            "UPDATE ledger_sheet SET title = $3, updated_at = CURRENT_TIMESTAMP "
            "WHERE workspace = $1 AND title = $2",
            workspace,
            title,
            new_name,
        )
        if status == "UPDATE 0":
            raise SheetNotFoundError(f"Sheet '{title}' not found")

    async def delete_sheet(self, workspace: str, title: str) -> None:
        status = await self.pool.execute(
            "DELETE FROM ledger_sheet WHERE workspace = $1 AND title = $2",
            workspace,
            title,
        )
        if status == "DELETE 0":
            raise SheetNotFoundError(f"Sheet '{title}' not found")

    async def mutate_grid(
        self,
        workspace: str,
        title: str,
        mutate: Callable[[list[list[Any]]], list[list[Any]]],
    ) -> list[list[Any]]:
        """Atomically apply a pure grid transform under a row lock.

        Args:
            workspace: Workspace the sheet belongs to.
            title: Sheet tab title.
            mutate: Pure function old_grid -> new_grid.

        Returns:
            The new grid.

        Raises:
            SheetNotFoundError: If the sheet does not exist.
        """
        async with self.pool.acquire() as conn:
            async with conn.transaction():
                row = await conn.fetchrow(
                    "SELECT sheet_id, grid FROM ledger_sheet "
                    "WHERE workspace = $1 AND title = $2 FOR UPDATE",
                    workspace,
                    title,
                )
                if row is None:
                    raise SheetNotFoundError(f"Sheet '{title}' not found")
                new_grid = mutate(json.loads(row["grid"]))
                await conn.execute(
                    "UPDATE ledger_sheet SET grid = $2, "
                    "updated_at = CURRENT_TIMESTAMP WHERE sheet_id = $1",
                    row["sheet_id"],
                    json.dumps(new_grid),
                )
                return new_grid
