"""Postgres-backed sheet storage for the ledger.

One row per sheet tab; the cell grid is a single JSONB 2D array. All
mutations run read-modify-write inside a transaction with FOR UPDATE row
locking, which preserves spreadsheet semantics with receipt-scale data
(hundreds of rows per tab). Revisit granularity only if tabs grow far
beyond that.
"""

from __future__ import annotations

import json
import logging
import os
from typing import Any, Callable, Optional

import asyncpg

logger = logging.getLogger(__name__)

DEFAULT_WORKSPACE = os.environ.get("LEDGER_WORKSPACE", "default")

_SCHEMA = """
CREATE TABLE IF NOT EXISTS ledger_sheet (
    sheet_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace TEXT NOT NULL,
    title TEXT NOT NULL,
    position INTEGER NOT NULL DEFAULT 0,
    grid JSONB NOT NULL DEFAULT '[]',
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (workspace, title)
);
"""


class SheetNotFoundError(Exception):
    """Raised when a sheet title does not exist in the workspace."""


class SheetExistsError(Exception):
    """Raised when creating a sheet whose title is already taken."""


class LedgerStore:
    """Sheet CRUD + grid read/modify/write on Postgres."""

    def __init__(self, dsn: str) -> None:
        self._dsn = dsn
        self._pool: asyncpg.Pool | None = None

    async def connect(self) -> None:
        self._pool = await asyncpg.create_pool(self._dsn, min_size=1, max_size=5)
        async with self._pool.acquire() as conn:
            await conn.execute(_SCHEMA)
        logger.info("Ledger store connected (schema applied)")

    async def close(self) -> None:
        if self._pool is not None:
            await self._pool.close()
            self._pool = None

    @property
    def pool(self) -> asyncpg.Pool:
        if self._pool is None:
            raise RuntimeError("Ledger store not connected")
        return self._pool

    async def list_sheets(self, workspace: str) -> list[dict[str, Any]]:
        rows = await self.pool.fetch(
            "SELECT sheet_id, title, position FROM ledger_sheet "
            "WHERE workspace = $1 ORDER BY position, sheet_id",
            workspace,
        )
        return [
            {"title": r["title"], "sheetId": r["sheet_id"], "index": i}
            for i, r in enumerate(rows)
        ]

    async def get_grid(self, workspace: str, title: str) -> list[list[Any]]:
        row = await self.pool.fetchrow(
            "SELECT grid FROM ledger_sheet WHERE workspace = $1 AND title = $2",
            workspace,
            title,
        )
        if row is None:
            raise SheetNotFoundError(f"Sheet '{title}' not found")
        return json.loads(row["grid"])

    async def create_sheet(
        self, workspace: str, title: str, grid: Optional[list[list[Any]]] = None
    ) -> dict[str, Any]:
        try:
            row = await self.pool.fetchrow(
                "INSERT INTO ledger_sheet (workspace, title, position, grid) "
                "VALUES ($1, $2, "
                "  COALESCE((SELECT MAX(position) + 1 FROM ledger_sheet "
                "            WHERE workspace = $1), 0), "
                "  $3) "
                "RETURNING sheet_id, title, position",
                workspace,
                title,
                json.dumps(grid or []),
            )
        except asyncpg.UniqueViolationError:
            raise SheetExistsError(f"Sheet '{title}' already exists") from None
        return {
            "sheetId": row["sheet_id"],
            "title": row["title"],
            "index": row["position"],
        }

    async def rename_sheet(self, workspace: str, title: str, new_name: str) -> None:
        status = await self.pool.execute(
            "UPDATE ledger_sheet SET title = $3, updated_at = CURRENT_TIMESTAMP "
            "WHERE workspace = $1 AND title = $2",
            workspace,
            title,
            new_name,
        )
        if status == "UPDATE 0":
            raise SheetNotFoundError(f"Sheet '{title}' not found")

    async def delete_sheet(self, workspace: str, title: str) -> None:
        status = await self.pool.execute(
            "DELETE FROM ledger_sheet WHERE workspace = $1 AND title = $2",
            workspace,
            title,
        )
        if status == "DELETE 0":
            raise SheetNotFoundError(f"Sheet '{title}' not found")

    async def mutate_grid(
        self,
        workspace: str,
        title: str,
        mutate: Callable[[list[list[Any]]], list[list[Any]]],
    ) -> list[list[Any]]:
        """Atomically apply a pure grid transform under a row lock.

        Args:
            workspace: Workspace the sheet belongs to.
            title: Sheet tab title.
            mutate: Pure function old_grid -> new_grid.

        Returns:
            The new grid.

        Raises:
            SheetNotFoundError: If the sheet does not exist.
        """
        async with self.pool.acquire() as conn:
            async with conn.transaction():
                row = await conn.fetchrow(
                    "SELECT sheet_id, grid FROM ledger_sheet "
                    "WHERE workspace = $1 AND title = $2 FOR UPDATE",
                    workspace,
                    title,
                )
                if row is None:
                    raise SheetNotFoundError(f"Sheet '{title}' not found")
                new_grid = mutate(json.loads(row["grid"]))
                await conn.execute(
                    "UPDATE ledger_sheet SET grid = $2, "
                    "updated_at = CURRENT_TIMESTAMP WHERE sheet_id = $1",
                    row["sheet_id"],
                    json.dumps(new_grid),
                )
                return new_grid
